# Generated by Django 4.2.3 on 2023-10-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0002_store1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store1',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='password',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='username',
        ),
        migrations.AddField(
            model_name='store',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,  # Remove this line
        ),
        migrations.AddField(
            model_name='store',
            name='dateofbirth',
            field=models.DateField(default='2023-01-01'),  # Provide a valid date as the default
            preserve_default=False,  # Remove this line
        ),
        migrations.AddField(
            model_name='store',
            name='gender',
            field=models.CharField(
                choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')],
                default='Male',  # Provide a valid default choice
                max_length=10,
            ),
            preserve_default=False,  # Remove this line
        ),
    ]
1