# Generated by Django 4.2.3 on 2023-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0003_delete_store1_rename_password_store_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='store1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=250)),
                ('password1', models.CharField(max_length=250)),
                ('confirmpassword', models.CharField(max_length=250)),
            ],
        ),
    ]
