# Generated by Django 4.2.3 on 2023-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0004_store1'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='store',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
