# Generated by Django 4.2.3 on 2023-10-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0005_store_address_store_email_store_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='department',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('IT', 'IT'), ('Business', 'Business')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
