# Generated by Django 4.2.3 on 2023-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0007_store_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='purpose',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place Order', 'Place Order'), ('Return', 'Return')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
