# Generated by Django 4.2.3 on 2023-10-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0008_store_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='materials',
            field=models.CharField(choices=[('NoteBook', 'NoteBook'), ('Pen', 'Pen'), ('Paper', 'Paper')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
