# Generated by Django 4.2.3 on 2023-10-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0009_store_materials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store1',
        ),
    ]
