# Generated by Django 4.2.3 on 2023-10-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgstoreapp', '0010_delete_store1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
